% This script loads the sim-data generated by the runSim scripts and
% demonstrates the results with appropriate plots.

ONLY_SPEED = true;
model_name = 'PM_Motor';
Ts = 1e-05;
% load('sim_data\Induction_Pos_Step.mat');
% load(fileName);

if(strcmp(modelName, 'Induction_Motor'))
    super_title = 'Induction Motor: Speed Control-Ramp Input';
else
    super_title = 'PM Motor';
end

%% Rotor Position and Rotor Speed Response
t = Angle(:,1);
if ONLY_SPEED
    figure(1); clf;
    %  plot(t, Speed_ref(:,2), t,Speed_ref(:,3));
    plotStepResponse(t, Speed_ref(:,2), Speed_ref(:,3));
    title(['Speed Response - Target = ',num2str(targetPer),'% the Nominal'],'Interpreter', 'none');
    xlabel('[sec]'); ylabel('[rpm]');
    suptitle(super_title);
else
    figure(1); clf;
    subplot(2,1,2); 
    plotStepResponse(t, Angle(:,2), Angle(:,3));
    title(['Angle Response- Target = ',num2str(Angle_Target)]);
    xlabel('[sec]'); ylabel('[deg]');
    e_ss = Angle(end,2)-Angle(end,3);
    disp(['Steady State Error = ', num2str(e_ss)]);
    
    
    subplot(2,1,1); 
%     plot(t, Speed_ref(:,2),t,Speed_ref(:,3));
    plotStepResponse(t, Speed_ref(:,2),Speed_ref(:,3));
    title(['Speed Response']);
%     xlabel('[sec]');
    ylabel('[rpm]');
    
    suptitle(super_title);
end
return
%% Torque and Torque Current Iq
figure(2); clf;
x = 1;
n = x-1;
t = Torque(:,1);
subplot(2,x,1); plot(t, Torque(:,2), t, Torque(:,3));
title('T_e: Electromagnetic Torque');
ylabel('[Nm]');
legend('measured','ref', 'location', 'best');

subplot(2,x,2);
t = Isd(:,1);
plot(t, Iabc_G(:,2:3));
title('I_q: Stator Torque Current');
ylabel('[A]');


%% Phase Current and Flux Current Id
figure(3); clf;
subplot(2,x,n+1);
t = Isd(:,1);
plot(t, Isd(:,2), t, Isd_ref(:,2));
title('I_d: Stator Field Current');
ylabel('[A]');
legend('measured','ref', 'location', 'best');
xlabel('[sec]');

subplot(2,x,n+2);
t = Iabc_G2(:,1);
plot(t, Iabc_G2(:,[2,5]));
title('I_A: Current of Line A');
ylabel('[A]');
xlabel('[sec]');

suptitle(super_title);

